### ISSUE TITLE
バージョン5.0.4の新しい機能について

### ISSUE THREAD

**Issue by kiyo31** [designet-inc-oss/SaMMA#1]
機能についての質問はこちらで良かったでしょうか。
PPAP対策で御社の開発されたSaMMa+NextCloudの環境が利用できないかと検討しております。
新しいバージョン(5.0.4)が先日リリースされ、安全化の方式を選択できるようになっています。
こちらをコンパイルし、テストを実施していますが、Aの宛先→os_uploaderを利用したオンラインストレージ、
Bの宛先→パスワードzipに設定したく、command.db,extention.dbを作成し、confファイル等も修正いたしました。

その際、TOが単一の場合(Aのみの場合 or Bのみの場合)は問題なく動作しますが、TOにAとBの宛先を指定した場合、
動作が不安定になります(Nextcloudへのアップロードにパスワードzipが含まれている、エラーでメール送信エラー、パスワードのテキストファイルのはずzipパスワードファイルになるなど)。

御社の環境において上記のような動作をすることはないでしょうか。
設定の誤りなのかもしれませんので、確認させていただけたらと思い、連絡させていただきました。

よろしくお願いいたします。

**Comment by designet-inc-oss** [comment]
ご連絡ありがとうございます。

上記に記載されている通り動作が不安定になる場合があることを確認しました。
修正致しますので今しばらくお待ちください。

よろしくお願いいたします。

**Comment by designet-inc-oss** [comment]
お待たせしており申し訳ございません。

ご連絡いただいた不具合などを修正したバージョン（5.0.5）をリリース致しました。
こちらをご利用いただければと思います。
よろしくお願いいたします。

**Comment by kiyo31** [comment]
修正ありがとうございました。
検証環境適用後問題なく動作することを確認いたしました。
引き続き動作についてご確認させていただきます。ありがとうございました。
